name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub gradio

      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo $HF_TOKEN | huggingface-cli login

      - name: Create space.yml if it doesn't exist
        run: |
          if [ ! -f "space.yml" ]; then
            echo "title: Q-Learning GridWorld Simulator" > space.yml
            echo "emoji: 🤖" >> space.yml
            echo "colorFrom: blue" >> space.yml
            echo "colorTo: green" >> space.yml
            echo "sdk: gradio" >> space.yml
            echo "sdk_version: 4.0.0" >> space.yml
            echo "app_file: rl_gradio.py" >> space.yml
          fi

      - name: Push to Hugging Face Space
        run: |
          # Create the space repo without prompting
          huggingface-cli repo create fahmizainal17/Q-Learning_GridWorld_Simulator --type space --visibility public || true
          
          # Push the space content to the Hugging Face Space
          huggingface-cli upload --repo fahmizainal17/Q-Learning_GridWorld_Simulator --repo-type space ./*

